### PR TITLE
`const` is immutable.

### PR DESCRIPTION
**Pull request by Bjeaurn**

### CODE REVIEW

**Comment by Bjeaurn** [comment]
No, I was wrong.

**Comment by mbeaudru** [comment]
Nope it's not :wink: , [let me quote MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const)

> The const declaration creates a read-only reference to a value. It does not mean the value it holds is immutable, just that the variable identifier cannot be reassigned. For instance, in the case where the content is an object, this means the object's contents (e.g., its parameters) can be altered.

**Comment by mbeaudru** [comment]
No problem :v:

**Comment by Bjeaurn** [comment]
However, if the referenced variable is also a `const`, can we not speak about implied immutability?

If it's `const` all the way down, isn't it all `immutable` as an effect?

**Comment by mbeaudru** [comment]
Unfortunately no, even with const all the way down you won't reach immutability of objects and arrays (since other primitives are by nature immutables).

You can reach objects immutability using Object.freeze, but it doesn't work recursively.

If you want to ensure your variables are immutable in all cases, you can use a library to handle this like [Seamless Immutable](https://github.com/rtfeldman/seamless-immutable) or [ImmutableJS](https://facebook.github.io/immutable-js/).

**Pull request closed without merging**
