### PR TITLE
Added Boolean to the cheatsheet

### PR DESCRIPTION
**Pull request by arguiot**
Added the new way of writing `true` and `false` in ES7:
- `true` === `!0`
- `false` === `!1`

### CODE REVIEW

**Comment by mbeaudru** [comment]
Hi @arguiot ! Thanks for helping making this documentation better :+1: .

This documentation is focusing on the notions *often* encountered in projects and doesn't try to be a language specification. I might be wrong, but I don't feel like this way of declaring a boolean is used by the community at the moment.

However, if it turns out I'm wrong I will consider merging the pull request if you make the following changes:

- External resources list at the end of the notion
- Remove the ```new Boolean``` part in the explanation, it's quite confusing (despite true), error prone and almost nobody uses booleans this way.

You can merge the "sample" and "explanation" section since it's a very short notion (example: [Function default parameter value](https://github.com/mbeaudru/modern-js-cheatsheet#function-default-parameter-value).

Besides, is it coming from ES6 or ES7 ?

Thanks :wink:

**Comment by arguiot** [comment]
Yes, I think 🤔 you’re right on some points. My PR was purely objective, I mean that because it’s a cheat sheet, I thought that even though a few people would use this method, it’s still interesting to know and to add, that is the all point of a cheat sheet, summarize documentation without missing any features, even tiny as this one. Ok, there is other bigger features (and I may do other PRs for them) but this one needs to be in it anyway. By the way, this feature is part of ES6.

Tell me if you agree with my point of view 😊.

Best regards, Arthur Guiot

**Comment by mbeaudru** [comment]
If you are incline to fix the points I suggested why not :+1:.

Like you said, it might be interesting to know after all :wink:.

**Comment by arguiot** [comment]
@mbeaudru It's fixed 😊.

**Comment by mbeaudru** [comment]
I've been thinking about this and I would like to do it a different way.

Indeed, I've done my research and it turns out this has not been introduced in ES6 because this behaviour is due to a boolean cast.

What might be added to the documentation is an explanation about "!" and "!!" operators and an overview of the boolean casting:

```js
!!"" // false -- empty string is casted to false
!!undefined // false
!!null // false
!!NaN // false
!!false // false
!!0 // false

// Everything else would be casted to true, for instance

!!1 // true
!!2 // true
```

This concept is called *[Truthy](https://developer.mozilla.org/en-US/docs/Glossary/Truthy) / [Falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy)* in JavaScript.

**Comment by arguiot** [comment]
@mbeaudru So, you want me to add this to the PR?

**Comment by mbeaudru** [comment]
Here is the structure I'm expecting for the PR:

### Truthy / Falsy

Description of the notion (false, 0, "", null, undefined, and NaN)

#### Explanation with sample code

- casting with "!" operator
- casting in ```if / else```

#### Resources

- MDN Truthy
- MDN Falsy

If you don't want to do it that's ok :+1: I will if you don't want to :wink:

**Comment by arguiot** [comment]
@mbeaudru Should be ok 👌 now! 😊

**Pull request merged**
