### PR TITLE
Corrected typo in `arguments`

### PR DESCRIPTION
**Pull request by huyz**

### CODE REVIEW

**Comment by tborowy** [comment]
please change this text in other files (languages)

**Comment by mbeaudru** [comment]
Usually, I won't ask for people to maintain translations when they catch up something to avoid discouraging participation. But this one is quick since it's just one word so yeah it would be nice and costless this time, do you mind @huyz ?

Thank you by the way 👍

**Comment by huyz** [comment]
Done

**Comment by mbeaudru** [comment]
Thank you ! 👍

**Pull request merged**
